name: Code Scanning

# How to call this workflow
# NOTE: DO NOT forget to set permissions
#jobs:
#  code-scanning:
#    uses: your-org/.github/.github/workflows/code-scanning.yml@main


on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches:
      - 'main'
      - 'releases/*'

env:
  solution: ./FGenerator.slnx  # Cannot recognize **/*.slnx

jobs:

  qodana:
    name: Qodana
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      pull-requests: write
      security-events: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0

      # Required for Build
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      # BUILD REQUIRED 
      - name: Build
        run: |
          dotnet run  --project cli -c Release -- build \
            --force --output  ./.z__merged_dll__ \
            "sample/*.cs" "FinalEnumGenerator/*.cs" "EnvObfuscator/*.cs" "MacroDotNet/*.cs"
          dnx -y FGenerator.Cli -- build \
            "test/*.cs" -f -o ./.z__merged_dll__
          dnx -y FGenerator.Cli -- build \
            "Unity/*.cs" -f -o ./.z__merged_dll__

      - uses: JetBrains/qodana-action@v2025.3
        with:
          upload-result: true
          pr-mode: false
          args: --apply-fixes,--solution,${{ env.solution }}
          push-fixes: pull-request
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

  inspectcode:
    name: ReSharper InspectCode
    runs-on: windows-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0

      # Required for ReSharper
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      # BUILD REQUIRED 
      - name: Build
        run: |
          dotnet run  --project cli -c Release -- build \
            --force --output  ./.z__merged_dll__ \
            "sample/*.cs" "FinalEnumGenerator/*.cs" "EnvObfuscator/*.cs" "MacroDotNet/*.cs"
          dnx -y FGenerator.Cli -- build \
            "test/*.cs" -f -o ./.z__merged_dll__
          dnx -y FGenerator.Cli -- build \
            "Unity/*.cs" -f -o ./.z__merged_dll__

      - uses: JetBrains/ReSharper-InspectCode@v0.11
        with:
          solution: ${{ env.solution }}
          output: inspectcode.sarif
          format: sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: inspectcode.sarif
