name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        unity: ["--unity", ""]
        merge: ["", "--merge"]
        configuration: ["", "-c Release"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.x.x

      - name: Build
        run: |
          dotnet run  --project cli ${{ matrix.configuration }} -- build \
            ${{ matrix.unity }} \
            ${{ matrix.merge }} \
            ${{ matrix.configuration }} \
            --force --output  ./.z__merged_dll__ \
            "sample/*.cs"  # enquote to prevent expanding

          dotnet run  --project cli ${{ matrix.configuration }} -- build \
            ${{ matrix.unity }} \
            ${{ matrix.merge }} \
            ${{ matrix.configuration }} \
            -f -o ./.z__merged_dll__ \
            "test/*.cs"

          dotnet run  --project cli ${{ matrix.configuration }} -- build \
            ${{ matrix.unity }} \
            ${{ matrix.merge }} \
            ${{ matrix.configuration }} \
            -f -o ./.z__merged_dll__ \
            "Unity/*.cs"

      - name: Pathfinder
        run: |
          ls -al ./.z__merged_dll__

      - name: Test
        run: |
          dotnet build         sandbox   ${{ matrix.configuration }} \
            -p:EmitCompilerGeneratedFiles=true \
            -p:CompilerGeneratedFilesOutputPath="../.generated"
          dotnet run --project sandbox   ${{ matrix.configuration }} --no-build -v:q -- -md >> $GITHUB_STEP_SUMMARY

      - uses: actions/upload-artifact@v4
        with:
          name: generated-sources${{ matrix.unity }}${{ matrix.merge }}${{ matrix.configuration }}
          path: ./.generated/**
          include-hidden-files: true
