name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  workflow_call:

jobs:

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        unity: ["--unity", ""]
        merge: ["", "--merge"]
        configuration: ["", "-c Release"]

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5      # v4.3.1
      - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9  # v4.3.1
        with:
          dotnet-version: 10.x.x

      - name: Build
        run: |
          dotnet run  --project cli ${{ matrix.configuration }} -- build \
            ${{ matrix.unity }} \
            ${{ matrix.merge }} \
            ${{ matrix.configuration }} \
            --force --output  ./.z__merged_dll__ \
            "sample/*.cs"  # enquote to prevent expanding

          dotnet run  --project cli ${{ matrix.configuration }} -- build \
            ${{ matrix.unity }} \
            ${{ matrix.merge }} \
            ${{ matrix.configuration }} \
            -f -o ./.z__merged_dll__ \
            "test/*.cs"

          dotnet run  --project cli ${{ matrix.configuration }} -- build \
            ${{ matrix.unity }} \
            ${{ matrix.merge }} \
            ${{ matrix.configuration }} \
            -f -o ./.z__merged_dll__ \
            "Unity/*.cs"

      - name: Pathfinder
        run: |
          ls -al ./.z__merged_dll__

      - name: Test
        run: |
          dotnet build         sandbox   ${{ matrix.configuration }} \
            -p:EmitCompilerGeneratedFiles=true \
            -p:CompilerGeneratedFilesOutputPath="../.generated"
          dotnet run --project sandbox   ${{ matrix.configuration }} --no-build -v:q -- -md >> $GITHUB_STEP_SUMMARY

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.job }}${{ matrix.unity }}${{ matrix.merge }}${{ matrix.configuration }}
          path: ./.generated/**
          include-hidden-files: true


  test-integration:

    # Don't run on push to main
    # --> It can fail while waiting for new FGenerator packages available.
    #     * Test still run on PR event.
    if: github.event_name != 'push'

    strategy:
      matrix:
        unity: ["--unity", ""]
        merge: ["", "--merge"]
        configuration: ["", "-c Release"]

    runs-on: ubuntu-latest   # tip: runs-on can use ${{ matrix.<name> }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5      # v4.3.1
      - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9  # v4.3.1
        with:
          dotnet-version: 10.x.x

      - name: Build
        run: |
          dnx -y FGenerator.Cli --prerelease -- build \
            ${{ matrix.unity }} \
            ${{ matrix.merge }} \
            ${{ matrix.configuration }} \
            --force --output  ./.z__merged_dll__ \
            "FinalEnumGenerator/*.cs" "EnvObfuscator/*.cs"  # enquote to prevent expanding

          dnx -y FGenerator.Cli --prerelease -- build \
            ${{ matrix.unity }} \
            ${{ matrix.merge }} \
            ${{ matrix.configuration }} \
            "test-integration/build-with-sdk.cs" -f -o ./.z__merged_dll__

      - name: Pathfinder
        run: |
          ls -al ./.z__merged_dll__

      - name: Test
        run: |
          dotnet build         EnvObfuscator.Test   ${{ matrix.configuration }} \
            -p:EmitCompilerGeneratedFiles=true \
            -p:CompilerGeneratedFilesOutputPath="../.generated"
          dotnet run --project EnvObfuscator.Test   ${{ matrix.configuration }} --no-build -v:q -- -md >> $GITHUB_STEP_SUMMARY

          dotnet build         FinalEnumGenerator.Test   ${{ matrix.configuration }} \
            -p:EmitCompilerGeneratedFiles=true \
            -p:CompilerGeneratedFilesOutputPath="../.generated"
          dotnet run --project FinalEnumGenerator.Test   ${{ matrix.configuration }} --no-build -v:q -- -md >> $GITHUB_STEP_SUMMARY

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.job }}${{ matrix.unity }}${{ matrix.merge }}${{ matrix.configuration }}
          path: ./.generated/**
          include-hidden-files: true
